# Generated by Django 4.2.11 on 2024-03-08 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GeoDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entomokey.country')),
            ],
        ),
        migrations.CreateModel(
            name='Habitats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SizeTypeInsect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_size', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeightTypeInsect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_size', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Insect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sci', models.CharField(max_length=200)),
                ('name_commom', models.CharField(max_length=200)),
                ('size', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('properties', models.TextField()),
                ('geo_distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entomokey.geodistribution')),
                ('habitats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entomokey.habitats')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entomokey.region')),
                ('size_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entomokey.sizetypeinsect')),
                ('weight_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entomokey.weighttypeinsect')),
            ],
        ),
        migrations.AddField(
            model_name='geodistribution',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entomokey.state'),
        ),
    ]
